# Generated by Django 4.0.1 on 2022-02-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('link', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Example: Auto Norte Estación Alcalá',
                        max_length=255,
                    ),
                ),
                (
                    'code',
                    models.CharField(help_text='Example: 19-1', max_length=50),
                ),
                (
                    'route_type',
                    models.CharField(
                        choices=[
                            ('transmilenio', 'TransMilenio'),
                            ('alimentador', 'Alimentador'),
                            ('urbano', 'Urbano'),
                            ('complementario', 'Complementario'),
                            ('especial', 'Especial'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        default='', help_text='Example: #95B734', max_length=50
                    ),
                ),
                ('schedule', models.CharField(max_length=500)),
                ('map_link', models.URLField(default='')),
                (
                    'details_link',
                    models.URLField(
                        default='',
                        help_text='Link to detail page on transmilenio.gov.co.',
                    ),
                ),
                (
                    'publication_date',
                    models.DateTimeField(
                        help_text='Data from transmilenio.gov.co.', null=True
                    ),
                ),
                ('last_update', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RouteStations',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'direction',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Recorrido 1'), (2, 'Recorrido 2')]
                    ),
                ),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'bus_station',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='route_stations',
                        to='routes.busstation',
                    ),
                ),
                (
                    'route',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='route_stations',
                        to='routes.route',
                    ),
                ),
            ],
            options={
                'ordering': ['direction', 'position'],
            },
        ),
    ]
