# Generated by Django 5.2.16 on 2026-08-24 03:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('stop_type', models.CharField(choices=[('estacion_troncal', 'Estación troncal'), ('paradero_zonal', 'Paradero zonal'), ('estacion_cable', 'Estación de cable')], max_length=20)),
                ('gtfs_stop_id', models.CharField(help_text='stops.txt stop_id — refresh natural key.', max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(default='', max_length=255)),
                ('link', models.URLField(default='')),
                ('cenefa', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('zona_sitp', models.CharField(blank=True, max_length=10)),
                ('audio', models.CharField(blank=True, max_length=255)),
                ('transmilenio_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('numero_vagones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_accesos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biciestacion', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cenefa__isnull', False), ('stop_type', 'paradero_zonal'), ('transmilenio_id__isnull', True)), models.Q(('cenefa__isnull', True), ('stop_type', 'estacion_troncal'), ('transmilenio_id__isnull', False)), models.Q(('cenefa__isnull', True), ('stop_type', 'estacion_cable'), ('transmilenio_id__isnull', True)), _connector='OR'), name='busstop_type_specific_fields_consistent')],
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Example: Calle 26', max_length=100, unique=True)),
                ('zone_letter', models.CharField(max_length=5)),
                ('color', models.CharField(help_text='Example: #95B734', max_length=50)),
                ('pdf_link', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('color__regex', '^#[0-9A-Fa-f]{6}$')), name='corridor_color_valid_hex')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Example: Auto Norte Estación Alcalá', max_length=255)),
                ('code', models.CharField(help_text='Example: 19-1', max_length=50)),
                ('gtfs_route_id', models.CharField(help_text='routes.txt route_id — refresh natural key.', max_length=50, unique=True)),
                ('route_mode', models.CharField(choices=[('transmilenio', 'TransMilenio'), ('transmizonal', 'TransMiZonal'), ('transmicable', 'TransMiCable')], max_length=20)),
                ('service_tier', models.CharField(choices=[('troncal', 'Troncal'), ('alimentador', 'Alimentador'), ('dual', 'Dual'), ('urbano', 'Urbano'), ('complementario', 'Complementario'), ('especial', 'Especial'), ('cable', 'Cable')], max_length=20)),
                ('color', models.CharField(default='', help_text='Example: #95B734', max_length=50)),
                ('path', django.contrib.gis.db.models.fields.MultiLineStringField(help_text='GTFS shape geometry.', null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('ciclovia_affected', models.BooleanField(default=False)),
                ('map_link', models.URLField(default='')),
                ('details_link', models.URLField(default='', help_text='Link to detail page on transmilenio.gov.co.')),
                ('publication_date', models.DateTimeField(help_text='Data from transmilenio.gov.co.', null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='routes.corridor')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_type', models.CharField(choices=[('L-V', 'Lunes a viernes'), ('SAB', 'Sábado'), ('L-S', 'Lunes a sábado'), ('DOM', 'Domingo'), ('L-V-D', 'Lunes a viernes y domingo'), ('SAB-DOM', 'Sábado y domingo'), ('DIARIO', 'Diario')], max_length=10)),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.PositiveSmallIntegerField(choices=[(1, 'Recorrido 1'), (2, 'Recorrido 2')])),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stations', to='routes.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stations', to='routes.route')),
            ],
            options={
                'ordering': ['route', 'direction', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('corridor__isnull', False), ('service_tier', 'troncal')), models.Q(models.Q(('service_tier', 'troncal'), _negated=True), ('corridor__isnull', True)), _connector='OR'), name='route_corridor_required_for_troncal_only'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('route_mode', 'transmilenio'), ('service_tier', 'troncal')), models.Q(('route_mode', 'transmilenio'), ('service_tier', 'alimentador')), models.Q(('route_mode', 'transmilenio'), ('service_tier', 'dual')), models.Q(('route_mode', 'transmizonal'), ('service_tier', 'urbano')), models.Q(('route_mode', 'transmizonal'), ('service_tier', 'complementario')), models.Q(('route_mode', 'transmizonal'), ('service_tier', 'especial')), models.Q(('route_mode', 'transmicable'), ('service_tier', 'cable')), _connector='OR'), name='route_mode_service_tier_valid_combination'),
        ),
        migrations.AddConstraint(
            model_name='routeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_type__in', ['L-V', 'SAB', 'L-S', 'DOM', 'L-V-D', 'SAB-DOM', 'DIARIO'])), name='routeschedule_day_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='routeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='routeschedule_end_after_start'),
        ),
    ]
