# Generated by Django 4.0.1 on 2022-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                (
                    'route_type',
                    models.CharField(
                        choices=[
                            ('transmilenio', 'TransMilenio'),
                            ('alimentador', 'Alimentador'),
                            ('urbano', 'Urbano'),
                            ('complementario', 'Complementario'),
                            ('especial', 'Especial'),
                        ],
                        max_length=50,
                    ),
                ),
                ('schedule', models.CharField(max_length=500)),
                ('map_link', models.URLField(default='')),
                ('details_link', models.URLField(default='')),
                ('publication_date', models.DateTimeField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
