# Generated by Django 4.0.1 on 2022-02-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestations',
            options={'ordering': ['route', 'direction', 'position']},
        ),
        migrations.AddField(
            model_name='busstation',
            name='audio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='busstation',
            name='cenefa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='busstation',
            name='latitud',
            field=models.DecimalField(
                decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name='busstation',
            name='longitud',
            field=models.DecimalField(
                decimal_places=15, max_digits=30, null=True
            ),
        ),
    ]
