# Generated by Django 4.0.1 on 2022-02-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'routes',
            '0002_alter_routestations_options_busstation_audio_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstation',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='busstation',
            old_name='longitud',
            new_name='longitude',
        ),
    ]
