# Generated by Django 4.0.1 on 2022-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_rename_latitud_busstation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
