# Generated by Django 4.0.1 on 2022-02-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_busstation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='transmilenio_id',
            field=models.IntegerField(null=True),
        ),
    ]
