# Generated by Django 4.0.1 on 2022-02-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_busstation_transmilenio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
